### ISSUE TITLE
Objective function in equation 2

### ISSUE THREAD

**Issue by zitongzhan** [locuslab/SATNet#11]
Hi,

Thanks for your fantastic work! I have a question related to the objective function in relaxation of maxsat. Why we want to minimize <S^T S, V^T V>? I treated the problem as MIN-UNSAT but still couldn't figure out. 

Thanks in advance!

**Comment by zitongzhan** [comment]
I found Po-Wei's another paper seems to answer this question: arxiv 1812.06362's equation 10. Am I right?

**Comment by xflash96** [comment]
Exactly. It's a "tightest" quadratic lower bound of the loss for the MIN-UNSAT / MAXSAT problem.
