### ISSUE TITLE
Question about the S matrix

### ISSUE THREAD

**Issue by zhaoyu-li** [locuslab/SATNet#15]
Hi,

Thanks for your exciting work! I also read your previous paper about the mixing method. However, it uses a weighted matrix C instead of the S matrix (or C = S^T S). I was wondering if we can backpropagate the gradient using the implicit differentiation theorem like SATNet if we use the matrix C (as the learnable parameter) instead of the matrix S. Or if we can just use auto diff to propagate the gradient as well?

Thank you!

**Comment by xflash96** [comment]
It's possible to derive implicit differentiation to the C matrix, although you may need to make it symmetric, i.e., only modeling the half-triangular part of the matrix. The S form is like modeling the MaxSat problem, and the C form is modeling graph weights.
