### ISSUE TITLE
Setup error with macOS Catalina 10.15.2

### ISSUE THREAD

**Issue by cyclone923** [locuslab/SATNet#7]
running install
running bdist_egg
running egg_info
creating satnet.egg-info
writing satnet.egg-info/PKG-INFO
writing dependency_links to satnet.egg-info/dependency_links.txt
writing requirements to satnet.egg-info/requires.txt
writing top-level names to satnet.egg-info/top_level.txt
writing manifest file 'satnet.egg-info/SOURCES.txt'
reading manifest file 'satnet.egg-info/SOURCES.txt'
writing manifest file 'satnet.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
running build_ext
/Users/yangchen/opt/miniconda3/envs/RL-Pytorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py:172: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++) is not compatible with the compiler Pytorch was
built with for this platform, which is clang++ on darwin. Please
use clang++ to to compile your extension. Alternatively, you may
compile PyTorch from source using g++, and then you can also use
g++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
building 'satnet._cpp' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/yangchen/opt/miniconda3/envs/PPO-PyTorch/include -arch x86_64 -I/Users/yangchen/opt/miniconda3/envs/PPO-PyTorch/include -arch x86_64 -I./src -I/Users/yangchen/opt/miniconda3/envs/RL-Pytorch/lib/python3.6/site-packages/torch/include -I/Users/yangchen/opt/miniconda3/envs/RL-Pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/Users/yangchen/opt/miniconda3/envs/RL-Pytorch/lib/python3.6/site-packages/torch/include/TH -I/Users/yangchen/opt/miniconda3/envs/RL-Pytorch/lib/python3.6/site-packages/torch/include/THC -I/Users/yangchen/opt/miniconda3/envs/RL-Pytorch/include/python3.6m -c src/satnet.cpp -o build/temp.macosx-10.7-x86_64-3.6/src/satnet.o -fopenmp -msse4.1 -Wall -g -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_cpp -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
clang: error: unsupported option '-fopenmp'
error: command 'gcc' failed with exit status 1

**Comment by cyclone923** [comment]
This error occurs when I run 

> python setup.py install

**Comment by cyclone923** [comment]
running install
running bdist_egg
running egg_info
writing satnet.egg-info/PKG-INFO
writing dependency_links to satnet.egg-info/dependency_links.txt
writing requirements to satnet.egg-info/requires.txt
writing top-level names to satnet.egg-info/top_level.txt
reading manifest file 'satnet.egg-info/SOURCES.txt'
writing manifest file 'satnet.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
running build_ext
/Users/yangchen/opt/miniconda3/envs/RL-Pytorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py:172: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++) is not compatible with the compiler Pytorch was
built with for this platform, which is clang++ on darwin. Please
use clang++ to to compile your extension. Alternatively, you may
compile PyTorch from source using g++, and then you can also use
g++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
building 'satnet._cpp' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/yangchen/opt/miniconda3/envs/PPO-PyTorch/include -arch x86_64 -I/Users/yangchen/opt/miniconda3/envs/PPO-PyTorch/include -arch x86_64 -I./src -I/Users/yangchen/opt/miniconda3/envs/RL-Pytorch/lib/python3.6/site-packages/torch/include -I/Users/yangchen/opt/miniconda3/envs/RL-Pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/Users/yangchen/opt/miniconda3/envs/RL-Pytorch/lib/python3.6/site-packages/torch/include/TH -I/Users/yangchen/opt/miniconda3/envs/RL-Pytorch/lib/python3.6/site-packages/torch/include/THC -I/Users/yangchen/opt/miniconda3/envs/RL-Pytorch/include/python3.6m -c src/satnet.cpp -o build/temp.macosx-10.7-x86_64-3.6/src/satnet.o -msse4.1 -Wall -g -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_cpp -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from src/satnet.cpp:4:
In file included from /Users/yangchen/opt/miniconda3/envs/RL-Pytorch/lib/python3.6/site-packages/torch/include/torch/extension.h:4:
In file included from /Users/yangchen/opt/miniconda3/envs/RL-Pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:3:
/Users/yangchen/opt/miniconda3/envs/RL-Pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/cuda.h:5:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 warning and 1 error generated.
error: command 'gcc' failed with exit status 1

**Comment by cyclone923** [comment]
I got this error when I delete the extra argument in extra_compile_args = ['-fopenmp', '-msse4.1', '-Wall', '-g']

**Comment by xflash96** [comment]
It looks like you're not using the same compiler that compiles PyTorch to compile the extension.
Would you try
1. brew install libomp (detailed instructions [here](https://iscinumpy.gitlab.io/post/omp-on-high-sierra/)
2. MACOSX_DEPLOYMENT_TARGET=10.15 CC=clang CXX=clang++ python setup.py install
and see if the above instructions work?

Also, you might also try [docker on Mac](https://docs.docker.com/docker-for-mac/install/),
which will always work.

**Comment by cyclone923** [comment]
> It looks like you're not using the same compiler that compiles PyTorch to compile the extension.
> Would you try
> 
> 1. brew install libomp (detailed instructions [here](https://iscinumpy.gitlab.io/post/omp-on-high-sierra/)
> 2. MACOSX_DEPLOYMENT_TARGET=10.15 CC=clang CXX=clang++ python setup.py install
>    and see if the above instructions work?
> 
> Also, you might also try [docker on Mac](https://docs.docker.com/docker-for-mac/install/), which will always work.

I successfully install satnet with libomp installed and running your 2nd instructions. Additionally, "-Xpreprocessor' is added to extra_compile_args. Thanks Po-wei!
