### ISSUE TITLE
Question about matrix S

### ISSUE THREAD

**Issue by huangdi95** [locuslab/SATNet#8]
Hi, your work is so brilliant！
However, I doubt about the value of S. It seems that the learnt S is not a ternary matrix right? If S is not ternary, then how can we say that it is the 'rule' learnt by the network?
Thanks!

**Comment by xflash96** [comment]
Yes, by the continuous nature of DL, the learnt clause matrix is not ternary.
It is a mixture of (weighted) ternary clause matrix. The SDP only depends on the gram matrix of S, that is, S'S.
BTW, you can encode known rules in matrix S by fixing part of matrix S, but decoding pure rules from S is not support for now.

**Comment by huangdi95** [comment]
Got it, thanks!
